name: "AnyLinux Tools Setup (Arch)"
description: "Downloads and installs Anylinux packaging tools and dependencies"
runs:
  using: "composite"
  steps:
    - name: Execute Setup Script
      shell: sh
      run: |
        sh "${GITHUB_ACTION_PATH}/setup.sh"
